#!/bin/bash

dir=$(find / -type d -name $1)
cd $dir; pwd

# ## get latest
# cd ~ git pull

# ## adding out files that we want to push
# git add $(pwd)

# ## use $1 as our comment message
git commit -m

# ## pushing our files to github
# git push -u origin main

echo $(date)