#!/bin/bash

read -p "Please enter the API TOKEN :" api_token


ssh_id="$(curl -X GET \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $api_token" \
  "https://api.digitalocean.com/v2/account/keys" | jq .ssh_keys[0].id)"


curl -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $api_token" \
  -d '{"name":"reviewSession","region":"nyc3","size":"s-1vcpu-1gb","image":"centos-7-x64","ssh_keys":["'"$ssh_id"'"]}' \
  "https://api.digitalocean.com/v2/droplets"


echo "Success"